baseurl = "/"
title = "CG"
theme = "ghostwriter"
languageCode = "fr-fr"
copyright = "Clément Gallet"

[Author]
    name = "Clément Gallet"

[Taxonomies]
    tag = "tags"
    topic = "topics"

[Params]
    intro = true
    headline = "Le blog de CG"
    description = "Où je parle de trucs"
    github = "https://github.com/clementgallet"
    twitter = "https://twitter.com/KilayeJV"
    twitch = "https://twitch.tv/kilaye"
    
[Permalinks]
    post = "/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Rubik"
    url = "/topics/rubik"
    weight = 2

[[menu.main]]
    name = "JV"
    url = "/topics/jv/"
    weight = 3

[[menu.main]]
    name = "Musique"
    url = "/topics/music/"
    weight = 4

[[menu.main]]
    name = "À propos"
    url = "/page/about/"
    weight = 5
